**ECOM90025 Assignment 1**

In [126]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

**Question 1**

Read the training sample to a Pandas dataframe.

In [15]:
url_train = "https://raw.githubusercontent.com/kkevinliu01/ECOM90025-A1/main/train.csv"
df_train = pd.read_csv(url_train, index_col=0)

In [16]:
df_train.head(5)

,Y,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X31,X32,X33,X34,X35,X36,X37,X38,X39,X40
ID,,,,,,,,,,,,,,,,,,,,,
0,0.532053,-0.148821,0.549597,0.272469,-0.901925,1.772201,-0.349480,-0.343701,0.190422,-0.834592,...,0.164693,-0.890457,0.781842,1.123592,-0.275561,-1.056807,0.299572,-1.639389,-1.517434,1.413109
1,5.184914,2.014094,-0.093027,-0.362052,0.456102,1.061241,-1.067338,0.643531,0.349825,-1.280970,...,-0.761800,-0.274411,0.673035,-0.631399,1.079935,0.839400,-0.042490,-0.588538,-0.456224,-2.120965
2,-1.432569,0.838779,-2.688285,-1.379352,-1.053576,-0.150720,1.079090,0.300199,0.234107,0.223405,...,0.299277,-0.186497,-1.439135,-0.744982,-0.577295,0.629026,0.349651,-0.014912,-0.007519,0.158457
3,5.187497,0.830986,-0.887702,1.387495,-0.228950,-1.753283,0.055467,1.159491,-2.459410,-1.363846,...,-0.470508,-0.801736,-0.325791,-0.757732,0.318284,-1.736215,-1.505948,0.207231,0.897713,0.664534
4,7.141232,1.209247,0.614855,-0.999241,-0.170428,-0.517563,-0.391593,-1.183876,0.907440,-0.287905,...,0.492473,-0.276980,-0.419119,0.025664,-0.165303,0.623124,1.151711,-0.622249,-0.873814,-1.110714

**Question 2**

Report the correlations of explanatory variables with the dependent variable $y$.

In [32]:
corr = df_train.corr(method = 'pearson')

In [33]:
corr = corr.drop(corr.columns[0], axis=1).head(1).T #remove correlation of y on y and take only correlations of x on y
corr

            Y
X1   0.454143
X2   0.422381
X3   0.139465
X4   0.141186
X5   0.115658
X6   0.165511
X7   0.136823
X8   0.084683
X9   0.187144
X10  0.089750
X11  0.013413
X12 -0.034959
X13 -0.002434
X14 -0.012638
X15  0.008358
X16  0.017756
X17  0.015071
X18 -0.033154
X19  0.025231
X20  0.015529
X21 -0.036947
X22 -0.054801
X23  0.028728
X24 -0.004212
X25 -0.016185
X26  0.006930
X27  0.022736
X28  0.024565
X29 -0.020314
X30  0.011942
X31 -0.025164
X32  0.078059
X33  0.006018
X34  0.011270
X35 -0.006686
X36 -0.001768
X37 -0.026539
X38  0.037148
X39 -0.008803
X40  0.024111

**Question 3**

Choose one explanatory variable, denoted by $y = \beta_0 + \beta_1 x + \epsilon$ , and estimate a simple linear model

In [75]:
corr_abs = abs(corr)

x_chosen = corr_abs.sort_values(by=['Y'], ascending=False).head(1).index.values[0] #find highest correlation variable

x_chosen

'X1'

In [85]:
df_estimate = df_train[["Y", x_chosen]]

df_estimate.head(5)

           Y        X1
ID
0   0.532053 -0.148821
1   5.184914  2.014094
2  -1.432569  0.838779
3   5.187497  0.830986
4   7.141232  1.209247

In [119]:
# estimate the linear model

length = df_estimate.shape[0]
X = df_estimate[x_chosen].values.reshape(length,1)
y = df_estimate["Y"].values.reshape(length,1)

reg = LinearRegression().fit(X, y)

b0 = reg.intercept_[0]

b1 = reg.coef_[0][0]

1.6769137807734174

**Question 4**

Use the estimtes of $\beta_0$ and $\beta_1$ and the testing sample to predict $y$.

In [136]:
url_test = "https://raw.githubusercontent.com/kkevinliu01/ECOM90025-A1/main/test.csv"
df_test = pd.read_csv(url_test, index_col=0)

length = df_test.shape[0]

df_test = df_test[x_chosen].values.reshape(length, 1)

predictions = reg.predict(df_test)

In [139]:
url_submission = "https://raw.githubusercontent.com/kkevinliu01/ECOM90025-A1/main/sample_submission.csv"
df_submission = pd.read_csv(url_submission, index_col=0)

df_submission["Y"] = predictions

df_submission.head(5)

             Y
ID
1400  4.228837
1401 -1.653391
1402 -0.690015
1403 -0.960029
1404  3.614204

**Question 5**

Submit your prediction file and get your Kaggle score screenshot.

In [141]:
df_submission.to_csv('submission.csv', index=True)